AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS Consultant Profile
Parameters:
  Environment:
    Type: String
Resources:
  ConsultantAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Environment}
      DefinitionBody:
        swagger: 2.0
        info:
          title:
            Ref: AWS::StackName
        x-amazon-apigateway-binary-media-types:
          - '*/*'
        paths:
          /profile:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConsultantLambda.Arn}/invocations
              responses: {}
  ConsultantLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ConsultantLambda-${Environment}
      Handler: profile.lambda_handler
      Runtime: python2.7 
      CodeUri: src 
      MemorySize: 128 
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess  
      Events:
        MyEndpoint:
          Type: Api 
          Properties:
            Path: /profile
            Method: get
            RestApiId:
              Ref: ConsultantAPI
      Environment:
        Variables:
          MyTableName: !Ref ConsultantTable
  ConsultantTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${S3Bucket}/*
      Bucket: !Ref S3Bucket
Outputs:
  WebsiteURL:
    Value: !GetAtt S3Bucket.WebsiteURL
    Description: URL for website hosted on S3
  ApiGWURL:
    Value: !Sub https://${ConsultantAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/profile
    Description: API Gateway endpoint